package ec.edu.espe.dailyDev.view;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import ec.edu.espe.dailyDev.model.Task;
import ec.edu.espe.dailyDev.model.User;
import ec.edu.espe.dailyDev.utils.DataFormatter;
import static ec.edu.espe.dailyDev.utils.FiltersHandler.createFilterTasksById;
import ec.edu.espe.dailyDev.utils.GPTHandler;
import ec.edu.espe.dailyDev.utils.MongoDBHandler;
import java.awt.Color;
import java.awt.Component;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import org.bson.conversions.Bson;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Olivier Paspuel
 */
public class Dashboard extends javax.swing.JFrame {

    private Point mPoint;

    /**
     * Creates new form Dashboard
     */
//    Bson filter = createFilterTasksById(User.getCurrentUserId().toString());
    Bson filter = createFilterTasksById("075dce30-9774-4ce0-800f-54fc24a821d0");

    List<Task> tasks = MongoDBHandler.findAllTasks(filter);

    public Dashboard() {
        initComponents();
//        Bson filter = createFilterTasksById(User.getCurrentUserId().toString());
        Bson filter = createFilterTasksById("075dce30-9774-4ce0-800f-54fc24a821d0");

        List<Task> tasks = MongoDBHandler.findAllTasks(filter);
        System.out.println(tasks);
        if (!tasks.isEmpty()) {
            createChart(statusChartIFrm, "status", tasks);
            createChart(priorityChartIFrm, "priority", tasks);
        }
        DefaultTableModel model = (DefaultTableModel) tasksTb.getModel();
        tasksTb.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int row = tasksTb.rowAtPoint(e.getPoint());
                int col = tasksTb.columnAtPoint(e.getPoint());
                if (row >= 0 && col == 0) {
                    String id = (String) tasksTb.getValueAt(row, col).toString();
                    Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
                    clipboard.setContents(new StringSelection(id), null);
                    JOptionPane.showMessageDialog(null, "ID copied: " + id);
                }
            }});
            for(Task task : tasks) {
            String formattedDate = DataFormatter.formatDate(task.getDueDate(), "yyyy/MM/dd");

                String completedStatus = DataFormatter.formatBooleanAsYesNo(task.isCompleted());

                model.addRow(new Object[]{task.getId(), task.getName(), task.getPriority(), formattedDate, completedStatus});
            }
        }

    public static void createChart(JInternalFrame frame, String type, List<Task> tasks) {

        BasicInternalFrameUI bi = (BasicInternalFrameUI) frame.getUI();
        bi.setNorthPane(null);

        DefaultPieDataset dataset = new DefaultPieDataset();

        for (Task task : tasks) {
            String category;
            if ("priority".equals(type)) {
                category = task.getPriority();
            } else if ("status".equals(type)) {
                category = task.isCompleted() ? "Completed" : "Not Completed";
            } else {
                throw new IllegalArgumentException("Unsupported type: " + type);
            }

            // Update dataset based on the category
            if (dataset.getKeys().contains(category)) {
                dataset.setValue(category, dataset.getValue(category).intValue() + 1);
            } else {
                dataset.setValue(category, 1);
            }
        }

        JFreeChart pieChart = ChartFactory.createPieChart("Tasks by " + (type.equals("priority") ? "Priority" : "Status"), dataset, true, true, false);
        ChartPanel chartPanel = new ChartPanel(pieChart);
        chartPanel.setPreferredSize(new java.awt.Dimension(500, 270));
        frame.setContentPane(chartPanel);
        frame.pack();
        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        actionBar = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        minimizeBtn = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        draggablePnl = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        username = new javax.swing.JLabel();
        dashboardActn = new javax.swing.JPanel();
        dashboardLbl = new javax.swing.JLabel();
        taskActn = new javax.swing.JPanel();
        taskLbl = new javax.swing.JLabel();
        scheduleActn = new javax.swing.JPanel();
        scheduleLbl = new javax.swing.JLabel();
        dailyActn = new javax.swing.JPanel();
        dailyLbl = new javax.swing.JLabel();
        adminActn = new javax.swing.JPanel();
        adminLbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TBPMain = new javax.swing.JTabbedPane();
        dashboardTab = new javax.swing.JPanel();
        dashboardTitlePnl = new javax.swing.JPanel();
        dashboardTitleLbl = new javax.swing.JLabel();
        currentTasksPnl = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        chartsPnl = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        statusChartIFrm = new javax.swing.JInternalFrame();
        priorityChartIFrm = new javax.swing.JInternalFrame();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tasksTab = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tasksTb = new javax.swing.JTable();
        taskActions = new javax.swing.JPanel();
        updateBtn1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        addTaskBtn = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        completeTaskBtn = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        scheduleTab = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        addMeeting = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        addSprint = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        completeTaskBtn3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        adminTab = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1080, 720));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        actionBar.setBackground(new java.awt.Color(0, 0, 0));
        actionBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitBtn.setBackground(new java.awt.Color(0, 0, 0));
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitBtnMousePressed(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/exitIconWhite.png"))); // NOI18N

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
            .addGroup(exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
        );

        actionBar.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 40, 41));

        minimizeBtn.setBackground(new java.awt.Color(0, 0, 0));
        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minimizeBtnMousePressed(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/minimizeIconWhite.png"))); // NOI18N

        javax.swing.GroupLayout minimizeBtnLayout = new javax.swing.GroupLayout(minimizeBtn);
        minimizeBtn.setLayout(minimizeBtnLayout);
        minimizeBtnLayout.setHorizontalGroup(
            minimizeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        minimizeBtnLayout.setVerticalGroup(
            minimizeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        actionBar.add(minimizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, -1));

        background.add(actionBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, -1, -1));

        draggablePnl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                draggablePnlMouseDragged(evt);
            }
        });
        draggablePnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                draggablePnlMousePressed(evt);
            }
        });
        background.add(draggablePnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 860, 70));

        sidebar.setBackground(new java.awt.Color(0, 0, 0));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        sidebar.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 230, -1));

        username.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/userIcon.png"))); // NOI18N
        username.setText("Robin Paspuel");
        username.setIconTextGap(11);
        sidebar.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 210, 70));

        dashboardActn.setBackground(new java.awt.Color(0, 0, 0));
        dashboardActn.setForeground(new java.awt.Color(255, 255, 255));
        dashboardActn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboardActn.setOpaque(false);
        dashboardActn.setPreferredSize(new java.awt.Dimension(220, 60));
        dashboardActn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardActnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardActnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardActnMouseExited(evt);
            }
        });

        dashboardLbl.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        dashboardLbl.setForeground(new java.awt.Color(255, 255, 255));
        dashboardLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dashboardLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/dashboardIcon.png"))); // NOI18N
        dashboardLbl.setText("Dashboard");
        dashboardLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        dashboardLbl.setIconTextGap(10);
        dashboardLbl.setPreferredSize(new java.awt.Dimension(220, 60));

        javax.swing.GroupLayout dashboardActnLayout = new javax.swing.GroupLayout(dashboardActn);
        dashboardActn.setLayout(dashboardActnLayout);
        dashboardActnLayout.setHorizontalGroup(
            dashboardActnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardActnLayout.createSequentialGroup()
                .addComponent(dashboardLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dashboardActnLayout.setVerticalGroup(
            dashboardActnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidebar.add(dashboardActn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 220, 60));

        taskActn.setBackground(new java.awt.Color(0, 0, 0));
        taskActn.setForeground(new java.awt.Color(255, 255, 255));
        taskActn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        taskActn.setOpaque(false);
        taskActn.setPreferredSize(new java.awt.Dimension(220, 60));
        taskActn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                taskActnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                taskActnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                taskActnMousePressed(evt);
            }
        });

        taskLbl.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        taskLbl.setForeground(new java.awt.Color(255, 255, 255));
        taskLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        taskLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/taskIcon.png"))); // NOI18N
        taskLbl.setText("Tasks");
        taskLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        taskLbl.setIconTextGap(10);
        taskLbl.setPreferredSize(new java.awt.Dimension(220, 60));

        javax.swing.GroupLayout taskActnLayout = new javax.swing.GroupLayout(taskActn);
        taskActn.setLayout(taskActnLayout);
        taskActnLayout.setHorizontalGroup(
            taskActnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taskActnLayout.createSequentialGroup()
                .addComponent(taskLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        taskActnLayout.setVerticalGroup(
            taskActnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(taskLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidebar.add(taskActn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 220, 60));

        scheduleActn.setBackground(new java.awt.Color(0, 0, 0));
        scheduleActn.setForeground(new java.awt.Color(255, 255, 255));
        scheduleActn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        scheduleActn.setOpaque(false);
        scheduleActn.setPreferredSize(new java.awt.Dimension(220, 60));
        scheduleActn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                scheduleActnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                scheduleActnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                scheduleActnMousePressed(evt);
            }
        });

        scheduleLbl.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        scheduleLbl.setForeground(new java.awt.Color(255, 255, 255));
        scheduleLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        scheduleLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/scheduleIcon.png"))); // NOI18N
        scheduleLbl.setText("Schedule");
        scheduleLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        scheduleLbl.setIconTextGap(10);
        scheduleLbl.setPreferredSize(new java.awt.Dimension(220, 60));

        javax.swing.GroupLayout scheduleActnLayout = new javax.swing.GroupLayout(scheduleActn);
        scheduleActn.setLayout(scheduleActnLayout);
        scheduleActnLayout.setHorizontalGroup(
            scheduleActnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scheduleActnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(scheduleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        scheduleActnLayout.setVerticalGroup(
            scheduleActnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scheduleActnLayout.createSequentialGroup()
                .addComponent(scheduleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sidebar.add(scheduleActn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        dailyActn.setBackground(new java.awt.Color(0, 0, 0));
        dailyActn.setForeground(new java.awt.Color(255, 255, 255));
        dailyActn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dailyActn.setOpaque(false);
        dailyActn.setPreferredSize(new java.awt.Dimension(220, 60));
        dailyActn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dailyActnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dailyActnMouseExited(evt);
            }
        });

        dailyLbl.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        dailyLbl.setForeground(new java.awt.Color(255, 255, 255));
        dailyLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dailyLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/dailyIcon.png"))); // NOI18N
        dailyLbl.setText("Daily Message");
        dailyLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        dailyLbl.setIconTextGap(10);
        dailyLbl.setPreferredSize(new java.awt.Dimension(220, 60));
        dailyLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dailyLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dailyActnLayout = new javax.swing.GroupLayout(dailyActn);
        dailyActn.setLayout(dailyActnLayout);
        dailyActnLayout.setHorizontalGroup(
            dailyActnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dailyActnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(dailyLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        dailyActnLayout.setVerticalGroup(
            dailyActnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dailyActnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(dailyLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        sidebar.add(dailyActn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 220, 60));

        adminActn.setBackground(new java.awt.Color(0, 0, 0));
        adminActn.setForeground(new java.awt.Color(255, 255, 255));
        adminActn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminActn.setOpaque(false);
        adminActn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminActnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminActnMouseExited(evt);
            }
        });

        adminLbl.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        adminLbl.setForeground(new java.awt.Color(255, 255, 255));
        adminLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        adminLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/adminIcon.png"))); // NOI18N
        adminLbl.setText("User Administration");
        adminLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        adminLbl.setIconTextGap(10);
        adminLbl.setPreferredSize(new java.awt.Dimension(220, 60));

        javax.swing.GroupLayout adminActnLayout = new javax.swing.GroupLayout(adminActn);
        adminActn.setLayout(adminActnLayout);
        adminActnLayout.setHorizontalGroup(
            adminActnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminActnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(adminLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        adminActnLayout.setVerticalGroup(
            adminActnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidebar.add(adminActn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 220, 60));

        background.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 720));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 860, 70));

        TBPMain.setBackground(new java.awt.Color(255, 255, 255));

        dashboardTab.setBackground(new java.awt.Color(217, 217, 217));

        dashboardTitlePnl.setBackground(new java.awt.Color(255, 255, 255));

        dashboardTitleLbl.setBackground(new java.awt.Color(255, 255, 255));
        dashboardTitleLbl.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        dashboardTitleLbl.setText("Dashboard");
        dashboardTitleLbl.setToolTipText("");
        dashboardTitleLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(7, 7, 7, 7));

        javax.swing.GroupLayout dashboardTitlePnlLayout = new javax.swing.GroupLayout(dashboardTitlePnl);
        dashboardTitlePnl.setLayout(dashboardTitlePnlLayout);
        dashboardTitlePnlLayout.setHorizontalGroup(
            dashboardTitlePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardTitleLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dashboardTitlePnlLayout.setVerticalGroup(
            dashboardTitlePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardTitleLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        currentTasksPnl.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Today's Pending Tasks", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Roboto Light", 0, 12))); // NOI18N
        jPanel8.setPreferredSize(new java.awt.Dimension(170, 30));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("1");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total Pending Tasks", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Roboto Light", 0, 12))); // NOI18N
        jPanel11.setPreferredSize(new java.awt.Dimension(170, 130));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("2");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Today's completed tasks", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Roboto Light", 0, 12))); // NOI18N
        jPanel12.setPreferredSize(new java.awt.Dimension(170, 30));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("2");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Next pending task", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Roboto Light", 0, 12))); // NOI18N
        jPanel13.setPreferredSize(new java.awt.Dimension(170, 30));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("<html>Create lambda function to handle dummy data in AWS </html>");
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel7.setPreferredSize(new java.awt.Dimension(93, 20));

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("High");

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel5.setText("Priority:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("See More");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout currentTasksPnlLayout = new javax.swing.GroupLayout(currentTasksPnl);
        currentTasksPnl.setLayout(currentTasksPnlLayout);
        currentTasksPnlLayout.setHorizontalGroup(
            currentTasksPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentTasksPnlLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        currentTasksPnlLayout.setVerticalGroup(
            currentTasksPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentTasksPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(currentTasksPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addGroup(currentTasksPnlLayout.createSequentialGroup()
                        .addGroup(currentTasksPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Daily", "Weekly", "Monthly", "Yearly", "All time", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Chart Tasks");

        statusChartIFrm.setBorder(null);
        statusChartIFrm.setPreferredSize(new java.awt.Dimension(300, 300));
        statusChartIFrm.setVisible(true);

        javax.swing.GroupLayout statusChartIFrmLayout = new javax.swing.GroupLayout(statusChartIFrm.getContentPane());
        statusChartIFrm.getContentPane().setLayout(statusChartIFrmLayout);
        statusChartIFrmLayout.setHorizontalGroup(
            statusChartIFrmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        statusChartIFrmLayout.setVerticalGroup(
            statusChartIFrmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        priorityChartIFrm.setBorder(null);
        priorityChartIFrm.setPreferredSize(new java.awt.Dimension(300, 300));
        priorityChartIFrm.setVisible(true);

        javax.swing.GroupLayout priorityChartIFrmLayout = new javax.swing.GroupLayout(priorityChartIFrm.getContentPane());
        priorityChartIFrm.getContentPane().setLayout(priorityChartIFrmLayout);
        priorityChartIFrmLayout.setHorizontalGroup(
            priorityChartIFrmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        priorityChartIFrmLayout.setVerticalGroup(
            priorityChartIFrmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Tasks stats");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(673, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout chartsPnlLayout = new javax.swing.GroupLayout(chartsPnl);
        chartsPnl.setLayout(chartsPnlLayout);
        chartsPnlLayout.setHorizontalGroup(
            chartsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chartsPnlLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(chartsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(chartsPnlLayout.createSequentialGroup()
                        .addComponent(priorityChartIFrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(statusChartIFrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(chartsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        chartsPnlLayout.setVerticalGroup(
            chartsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chartsPnlLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(chartsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(priorityChartIFrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusChartIFrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(chartsPnlLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dashboardTabLayout = new javax.swing.GroupLayout(dashboardTab);
        dashboardTab.setLayout(dashboardTabLayout);
        dashboardTabLayout.setHorizontalGroup(
            dashboardTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashboardTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chartsPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(currentTasksPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dashboardTitlePnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        dashboardTabLayout.setVerticalGroup(
            dashboardTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashboardTitlePnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentTasksPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chartsPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TBPMain.addTab("tab1", dashboardTab);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel12.setText("Tasks");
        jLabel12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tasksTb.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        tasksTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Priority", "Due date", "Completed"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tasksTb.setCellEditor(null);
        jScrollPane1.setViewportView(tasksTb);

        taskActions.setBackground(new java.awt.Color(255, 255, 255));

        updateBtn1.setBackground(new java.awt.Color(0, 0, 0));
        updateBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                updateBtn1MousePressed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Print All Tasks");

        javax.swing.GroupLayout updateBtn1Layout = new javax.swing.GroupLayout(updateBtn1);
        updateBtn1.setLayout(updateBtn1Layout);
        updateBtn1Layout.setHorizontalGroup(
            updateBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
            .addGroup(updateBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );
        updateBtn1Layout.setVerticalGroup(
            updateBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(updateBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
        );

        addTaskBtn.setBackground(new java.awt.Color(0, 0, 0));
        addTaskBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addTaskBtnMousePressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Add Task");

        javax.swing.GroupLayout addTaskBtnLayout = new javax.swing.GroupLayout(addTaskBtn);
        addTaskBtn.setLayout(addTaskBtnLayout);
        addTaskBtnLayout.setHorizontalGroup(
            addTaskBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
            .addGroup(addTaskBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
        );
        addTaskBtnLayout.setVerticalGroup(
            addTaskBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(addTaskBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );

        completeTaskBtn.setBackground(new java.awt.Color(0, 0, 0));
        completeTaskBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                completeTaskBtnMousePressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Complete Task");

        javax.swing.GroupLayout completeTaskBtnLayout = new javax.swing.GroupLayout(completeTaskBtn);
        completeTaskBtn.setLayout(completeTaskBtnLayout);
        completeTaskBtnLayout.setHorizontalGroup(
            completeTaskBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
            .addGroup(completeTaskBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
        );
        completeTaskBtnLayout.setVerticalGroup(
            completeTaskBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
            .addGroup(completeTaskBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
        );

        deleteBtn.setBackground(new java.awt.Color(0, 0, 0));
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deleteBtnMousePressed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Delete Task");

        javax.swing.GroupLayout deleteBtnLayout = new javax.swing.GroupLayout(deleteBtn);
        deleteBtn.setLayout(deleteBtnLayout);
        deleteBtnLayout.setHorizontalGroup(
            deleteBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
            .addGroup(deleteBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );
        deleteBtnLayout.setVerticalGroup(
            deleteBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(deleteBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
        );

        updateBtn.setBackground(new java.awt.Color(0, 0, 0));
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                updateBtnMousePressed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Update Task");

        javax.swing.GroupLayout updateBtnLayout = new javax.swing.GroupLayout(updateBtn);
        updateBtn.setLayout(updateBtnLayout);
        updateBtnLayout.setHorizontalGroup(
            updateBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
            .addGroup(updateBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );
        updateBtnLayout.setVerticalGroup(
            updateBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(updateBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout taskActionsLayout = new javax.swing.GroupLayout(taskActions);
        taskActions.setLayout(taskActionsLayout);
        taskActionsLayout.setHorizontalGroup(
            taskActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskActionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(taskActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addTaskBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(completeTaskBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        taskActionsLayout.setVerticalGroup(
            taskActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskActionsLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(addTaskBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(completeTaskBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel18.setFont(new java.awt.Font("Roboto Light", 0, 13)); // NOI18N
        jLabel18.setText("Click a task to copy its id");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(465, 465, 465)))
                .addComponent(taskActions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(taskActions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout tasksTabLayout = new javax.swing.GroupLayout(tasksTab);
        tasksTab.setLayout(tasksTabLayout);
        tasksTabLayout.setHorizontalGroup(
            tasksTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tasksTabLayout.setVerticalGroup(
            tasksTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tasksTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TBPMain.addTab("tab3", tasksTab);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel15.setText("Schedule");
        jLabel15.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        addMeeting.setBackground(new java.awt.Color(0, 0, 0));
        addMeeting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addMeetingMousePressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Add Meeting");

        javax.swing.GroupLayout addMeetingLayout = new javax.swing.GroupLayout(addMeeting);
        addMeeting.setLayout(addMeetingLayout);
        addMeetingLayout.setHorizontalGroup(
            addMeetingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(addMeetingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
        );
        addMeetingLayout.setVerticalGroup(
            addMeetingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(addMeetingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );

        addSprint.setBackground(new java.awt.Color(0, 0, 0));
        addSprint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addSprintMousePressed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Add Sprint");

        javax.swing.GroupLayout addSprintLayout = new javax.swing.GroupLayout(addSprint);
        addSprint.setLayout(addSprintLayout);
        addSprintLayout.setHorizontalGroup(
            addSprintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(addSprintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
        );
        addSprintLayout.setVerticalGroup(
            addSprintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(addSprintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );

        completeTaskBtn3.setBackground(new java.awt.Color(0, 0, 0));
        completeTaskBtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                completeTaskBtn3MousePressed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Add Reminder");

        javax.swing.GroupLayout completeTaskBtn3Layout = new javax.swing.GroupLayout(completeTaskBtn3);
        completeTaskBtn3.setLayout(completeTaskBtn3Layout);
        completeTaskBtn3Layout.setHorizontalGroup(
            completeTaskBtn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 183, Short.MAX_VALUE)
            .addGroup(completeTaskBtn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(completeTaskBtn3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)))
        );
        completeTaskBtn3Layout.setVerticalGroup(
            completeTaskBtn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
            .addGroup(completeTaskBtn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addMeeting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addSprint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(completeTaskBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(addMeeting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addSprint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(completeTaskBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(423, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout scheduleTabLayout = new javax.swing.GroupLayout(scheduleTab);
        scheduleTab.setLayout(scheduleTabLayout);
        scheduleTabLayout.setHorizontalGroup(
            scheduleTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(scheduleTabLayout.createSequentialGroup()
                .addGap(665, 665, 665)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        scheduleTabLayout.setVerticalGroup(
            scheduleTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scheduleTabLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TBPMain.addTab("tab4", scheduleTab);

        javax.swing.GroupLayout adminTabLayout = new javax.swing.GroupLayout(adminTab);
        adminTab.setLayout(adminTabLayout);
        adminTabLayout.setHorizontalGroup(
            adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        adminTabLayout.setVerticalGroup(
            adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );

        TBPMain.addTab("tab5", adminTab);

        background.add(TBPMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 860, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void handleMouseEnter(Component component, JLabel label, String iconPath) {
        component.setBackground(Color.WHITE);
        label.setForeground(Color.BLACK);
        label.setIcon(new javax.swing.ImageIcon(getClass().getResource(iconPath)));
    }

    private void handleMouseExit(Component component, JLabel label, String iconPath) {
        component.setBackground(Color.BLACK);
        label.setForeground(Color.WHITE);
        label.setIcon(new javax.swing.ImageIcon(getClass().getResource(iconPath)));
    }

    private void adminActnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminActnMouseEntered
        handleMouseEnter(adminActn, adminLbl, "/imgs/adminIconBlack.png");
    }//GEN-LAST:event_adminActnMouseEntered

    private void dailyActnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dailyActnMouseEntered
        handleMouseEnter(dailyActn, dailyLbl, "/imgs/dailyIconBlack.png");
    }//GEN-LAST:event_dailyActnMouseEntered

    private void scheduleActnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scheduleActnMouseEntered
        handleMouseEnter(scheduleActn, scheduleLbl, "/imgs/scheduleIconBlack.png");
    }//GEN-LAST:event_scheduleActnMouseEntered

    private void taskActnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taskActnMouseEntered
        handleMouseEnter(taskActn, taskLbl, "/imgs/taskIconBlack.png");
    }//GEN-LAST:event_taskActnMouseEntered

    private void dashboardActnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardActnMouseExited
        handleMouseExit(dashboardActn, dashboardLbl, "/imgs/dashboardIcon.png");
    }//GEN-LAST:event_dashboardActnMouseExited

    private void taskActnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taskActnMouseExited
        handleMouseExit(taskActn, taskLbl, "/imgs/taskIcon.png");
    }//GEN-LAST:event_taskActnMouseExited

    private void scheduleActnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scheduleActnMouseExited
        handleMouseExit(scheduleActn, scheduleLbl, "/imgs/scheduleIcon.png");
    }//GEN-LAST:event_scheduleActnMouseExited

    private void dailyActnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dailyActnMouseExited
        handleMouseExit(dailyActn, dailyLbl, "/imgs/dailyIcon.png");
    }//GEN-LAST:event_dailyActnMouseExited

    private void adminActnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminActnMouseExited
        handleMouseExit(adminActn, adminLbl, "/imgs/adminIcon.png");
    }//GEN-LAST:event_adminActnMouseExited

    private void dashboardActnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardActnMouseEntered
        handleMouseEnter(dashboardActn, dashboardLbl, "/imgs/dashboardIconBlack.png");
    }//GEN-LAST:event_dashboardActnMouseEntered

    private void dashboardActnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardActnMouseClicked
        JOptionPane.showMessageDialog(rootPane, User.getCurrentUserId());

    }//GEN-LAST:event_dashboardActnMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void dailyLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dailyLblMouseClicked

        String gptS = GPTHandler.getDailyMessage(tasks);
//                .replaceAll("\n", "<br>");
        GPTRes pnl = new GPTRes();
        pnl.getMyLabel().setText(gptS);
        pnl.setVisible(true);
        JOptionPane.showMessageDialog(rootPane, gptS);

    }//GEN-LAST:event_dailyLblMouseClicked

    private void exitBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMousePressed
        System.exit(0);
    }//GEN-LAST:event_exitBtnMousePressed

    private void minimizeBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMousePressed
        this.setState(Dashboard.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnMousePressed

    private void draggablePnlMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_draggablePnlMouseDragged
        int currentX = this.getLocation().x;
        int currentY = this.getLocation().y;
        int moveX = (currentX + evt.getX()) - (currentX + mPoint.x);
        int moveY = (currentY + evt.getY()) - (currentY + mPoint.y);

        int x = currentX + moveX;
        int y = currentY + moveY;
        this.setLocation(x, y);
    }//GEN-LAST:event_draggablePnlMouseDragged

    private void draggablePnlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_draggablePnlMousePressed
        mPoint = evt.getPoint();
        getComponentAt(mPoint);
    }//GEN-LAST:event_draggablePnlMousePressed

    private void taskActnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taskActnMousePressed
        TBPMain.setSelectedIndex(1);
    }//GEN-LAST:event_taskActnMousePressed

    private void addTaskBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTaskBtnMousePressed
        FrmTask frm = new FrmTask(this);
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addTaskBtnMousePressed

    private void completeTaskBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_completeTaskBtnMousePressed

        FrmCompleteTask complete = new FrmCompleteTask();
        complete.setVisible(true);

    }//GEN-LAST:event_completeTaskBtnMousePressed

    private void scheduleActnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scheduleActnMousePressed
        TBPMain.setSelectedIndex(2);
    }//GEN-LAST:event_scheduleActnMousePressed

    private void addMeetingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMeetingMousePressed
        FrmMeeting meeting = new FrmMeeting();
        meeting.setVisible(true);

    }//GEN-LAST:event_addMeetingMousePressed

    private void addSprintMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSprintMousePressed
        FrmSprint sprint = new FrmSprint();
        sprint.setVisible(true);
    }//GEN-LAST:event_addSprintMousePressed

    private void completeTaskBtn3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_completeTaskBtn3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_completeTaskBtn3MousePressed

    private void deleteBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnMousePressed

    private void updateBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateBtnMousePressed

    private void updateBtn1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtn1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateBtn1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        FlatLaf.registerCustomDefaultsSource("view");
        FlatLightLaf.setup();
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TBPMain;
    private javax.swing.JPanel actionBar;
    private javax.swing.JPanel addMeeting;
    private javax.swing.JPanel addSprint;
    private javax.swing.JPanel addTaskBtn;
    private javax.swing.JPanel adminActn;
    private javax.swing.JLabel adminLbl;
    private javax.swing.JPanel adminTab;
    private javax.swing.JPanel background;
    private javax.swing.JPanel chartsPnl;
    private javax.swing.JPanel completeTaskBtn;
    private javax.swing.JPanel completeTaskBtn3;
    private javax.swing.JPanel currentTasksPnl;
    private javax.swing.JPanel dailyActn;
    private javax.swing.JLabel dailyLbl;
    private javax.swing.JPanel dashboardActn;
    private javax.swing.JLabel dashboardLbl;
    private javax.swing.JPanel dashboardTab;
    private javax.swing.JLabel dashboardTitleLbl;
    private javax.swing.JPanel dashboardTitlePnl;
    private javax.swing.JPanel deleteBtn;
    private javax.swing.JLabel draggablePnl;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel minimizeBtn;
    private javax.swing.JInternalFrame priorityChartIFrm;
    private javax.swing.JPanel scheduleActn;
    private javax.swing.JLabel scheduleLbl;
    private javax.swing.JPanel scheduleTab;
    private javax.swing.JPanel sidebar;
    private javax.swing.JInternalFrame statusChartIFrm;
    private javax.swing.JPanel taskActions;
    private javax.swing.JPanel taskActn;
    private javax.swing.JLabel taskLbl;
    private javax.swing.JPanel tasksTab;
    private javax.swing.JTable tasksTb;
    private javax.swing.JPanel updateBtn;
    private javax.swing.JPanel updateBtn1;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
