/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.ViveresGabySK.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Alex Cuzco, HoneyBadgers, DCCO-ESPE
 */
public class FrmViveresGaby extends javax.swing.JFrame {

    /**
     * Creates new form FrmViveresGaby
     */
    public FrmViveresGaby() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuViveresGaby = new javax.swing.JMenu();
        itemCloseSession = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        mnuProducts = new javax.swing.JMenu();
        itemRegisterProduct = new javax.swing.JMenuItem();
        mnuCategories = new javax.swing.JMenu();
        itemRegister = new javax.swing.JMenuItem();
        itemViewCategories = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        btnClients = new javax.swing.JMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenuItem1.setText("jMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuViveresGaby.setText("Viveres Gaby");

        itemCloseSession.setText("logout");
        itemCloseSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCloseSessionActionPerformed(evt);
            }
        });
        mnuViveresGaby.add(itemCloseSession);

        jMenuItem3.setText("exit");
        mnuViveresGaby.add(jMenuItem3);

        jMenuBar1.add(mnuViveresGaby);

        mnuProducts.setText("Product");

        itemRegisterProduct.setText("Register");
        itemRegisterProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegisterProductActionPerformed(evt);
            }
        });
        mnuProducts.add(itemRegisterProduct);

        jMenuBar1.add(mnuProducts);

        mnuCategories.setText("Categories");

        itemRegister.setText("Register");
        itemRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegisterActionPerformed(evt);
            }
        });
        mnuCategories.add(itemRegister);

        itemViewCategories.setText("View Categories");
        itemViewCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemViewCategoriesActionPerformed(evt);
            }
        });
        mnuCategories.add(itemViewCategories);

        jMenuBar1.add(mnuCategories);

        jMenu4.setText("Clients");

        btnClients.setText("View clients");
        btnClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientsActionPerformed(evt);
            }
        });
        jMenu4.add(btnClients);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCloseSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCloseSessionActionPerformed
    int selection = 0;
    JOptionPane.showConfirmDialog(rootPane, "Are you sure?");
    if (selection==JOptionPane.YES_NO_OPTION){
        FrmLogin frmLogin = new FrmLogin();
        this.setVisible(false);
        frmLogin.setVisible(true);
    }else if (selection==1){
    
    }else if (selection==2){
    }
    
    // TODO add your handling code here:
    }//GEN-LAST:event_itemCloseSessionActionPerformed

    private void itemViewCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemViewCategoriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemViewCategoriesActionPerformed

    private void itemRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegisterActionPerformed
    FrmCategories frmCategories = new FrmCategories();
    this.setVisible(false);
    frmCategories.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_itemRegisterActionPerformed

    private void itemRegisterProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegisterProductActionPerformed
    FrmProduct frmProduct = new FrmProduct();
    this.setVisible(false);
    frmProduct.setVisible(true);
    
    
    // TODO add your handling code here:
    }//GEN-LAST:event_itemRegisterProductActionPerformed

    private void btnClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientsActionPerformed
    FrmClients frmClients =new  FrmClients();
    this.setVisible(false);
    frmClients.setVisible(true); 
    
    // TODO add your handling code here:
    }//GEN-LAST:event_btnClientsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmViveresGaby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmViveresGaby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmViveresGaby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmViveresGaby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmViveresGaby().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnClients;
    private javax.swing.JMenuItem itemCloseSession;
    private javax.swing.JMenuItem itemRegister;
    private javax.swing.JMenuItem itemRegisterProduct;
    private javax.swing.JMenuItem itemViewCategories;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JMenu mnuCategories;
    private javax.swing.JMenu mnuProducts;
    private javax.swing.JMenu mnuViveresGaby;
    // End of variables declaration//GEN-END:variables
}
