package ec.edu.espe.vehicle.view;


import ec.edu.espe.vehicle.controller.Manager;
import ec.edu.espe.vehicle.model.Vehicles;
import javax.swing.JOptionPane;

/**
 *
 * @author Rony
 */
public class FrmFindVehicle extends javax.swing.JFrame {

    private Vehicles vehicle;
    /**
     * Creates new form FrmFind
     */
    public FrmFindVehicle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnFind = new javax.swing.JPanel();
        txtFindbtn = new javax.swing.JLabel();
        spnId = new javax.swing.JSpinner();
        txtTotalCost = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        txtHiringCost = new javax.swing.JLabel();
        txtPresentedHours = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setMaximumSize(new java.awt.Dimension(385, 420));
        background.setMinimumSize(new java.awt.Dimension(385, 420));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Total:");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Id:");
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Marca:");
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Costo de uso:");
        background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Horas de alquiler:");
        background.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, 20));

        btnFind.setBackground(new java.awt.Color(207, 207, 207));

        txtFindbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFindbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtFindbtn.setText("Buscar");
        txtFindbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtFindbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFindbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnFindLayout = new javax.swing.GroupLayout(btnFind);
        btnFind.setLayout(btnFindLayout);
        btnFindLayout.setHorizontalGroup(
            btnFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnFindLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtFindbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnFindLayout.setVerticalGroup(
            btnFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnFindLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtFindbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background.add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 150, 40));

        spnId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        spnId.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        background.add(spnId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 80, 30));

        txtTotalCost.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTotalCost.setText("0,00");
        txtTotalCost.setMaximumSize(new java.awt.Dimension(170, 20));
        txtTotalCost.setMinimumSize(new java.awt.Dimension(170, 20));
        txtTotalCost.setName(""); // NOI18N
        txtTotalCost.setPreferredSize(new java.awt.Dimension(170, 20));
        background.add(txtTotalCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 120, -1));

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtName.setMaximumSize(new java.awt.Dimension(170, 20));
        txtName.setMinimumSize(new java.awt.Dimension(170, 20));
        txtName.setName(""); // NOI18N
        txtName.setPreferredSize(new java.awt.Dimension(170, 20));
        background.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        txtHiringCost.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHiringCost.setMaximumSize(new java.awt.Dimension(170, 20));
        txtHiringCost.setMinimumSize(new java.awt.Dimension(170, 20));
        txtHiringCost.setName(""); // NOI18N
        txtHiringCost.setPreferredSize(new java.awt.Dimension(170, 20));
        background.add(txtHiringCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 150, -1));

        txtPresentedHours.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPresentedHours.setMaximumSize(new java.awt.Dimension(170, 20));
        txtPresentedHours.setMinimumSize(new java.awt.Dimension(170, 20));
        txtPresentedHours.setName(""); // NOI18N
        txtPresentedHours.setPreferredSize(new java.awt.Dimension(170, 20));
        background.add(txtPresentedHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 150, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Encontrar Vehiculo");
        background.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        background.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 352, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFindbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFindbtnMouseClicked
        int idSearch = Integer.parseInt(spnId.getValue().toString());
        
        Manager singcont = new Manager();
        vehicle = singcont.find(idSearch);
        
        if(vehicle.getId()<= 0){
            JOptionPane.showConfirmDialog(null, "Cantante no encontrado",
                "ERROR_MESSAGE", JOptionPane.OK_OPTION,
                JOptionPane.ERROR_MESSAGE);
        }else{
            txtName.setText(vehicle.getBrand());
            txtHiringCost.setText(String.valueOf(vehicle.getRentalCost()));
            txtPresentedHours.setText(String.valueOf(vehicle.getHourlyUse()));
        
            float cost = singcont.getTotalCost(vehicle);
            txtTotalCost.setText(String.valueOf(cost));
        }
    }//GEN-LAST:event_txtFindbtnMouseClicked

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
       FrmVehicle frmVehicle = new FrmVehicle();
       frmVehicle.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFindVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFindVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFindVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFindVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFindVehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel btnFind;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSpinner spnId;
    private javax.swing.JLabel txtFindbtn;
    private javax.swing.JLabel txtHiringCost;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtPresentedHours;
    private javax.swing.JLabel txtTotalCost;
    // End of variables declaration//GEN-END:variables
}
