/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.espe.edu.farRestaurant.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Mateo Gabriel Criollo/OOP14575/InterByte
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MnuFarRestaurant = new javax.swing.JMenu();
        MnuClose = new javax.swing.JMenuItem();
        MnuSesion = new javax.swing.JMenuItem();
        MnuCustomer = new javax.swing.JMenu();
        ItemRegisterCustomer = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        ItemRegisterChef = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuOrder = new javax.swing.JMenu();
        itemOrdering = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MnuFarRestaurant.setText("Far Restaurant");

        MnuClose.setText("Close");
        MnuFarRestaurant.add(MnuClose);

        MnuSesion.setText("Log out");
        MnuSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuSesionActionPerformed(evt);
            }
        });
        MnuFarRestaurant.add(MnuSesion);

        jMenuBar1.add(MnuFarRestaurant);

        MnuCustomer.setText("Customer");

        ItemRegisterCustomer.setText("Register");
        ItemRegisterCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemRegisterCustomerActionPerformed(evt);
            }
        });
        MnuCustomer.add(ItemRegisterCustomer);

        jMenuBar1.add(MnuCustomer);

        jMenu1.setText("Chef");

        ItemRegisterChef.setText("Register");
        ItemRegisterChef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemRegisterChefActionPerformed(evt);
            }
        });
        jMenu1.add(ItemRegisterChef);

        jMenuItem2.setText("Ver Ordenes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Dish");

        jMenuItem1.setText("Visualizar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        mnuOrder.setText("Order");

        itemOrdering.setText("Realizar Orden");
        itemOrdering.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOrderingActionPerformed(evt);
            }
        });
        mnuOrder.add(itemOrdering);

        jMenuBar1.add(mnuOrder);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemRegisterCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemRegisterCustomerActionPerformed
        FrmCustomer frmCustomer = new FrmCustomer();
        this.setVisible(false);
        frmCustomer.setVisible(true);
    }//GEN-LAST:event_ItemRegisterCustomerActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmDish frmDish = new FrmDish();
        this.setVisible(false);
        frmDish.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MnuSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuSesionActionPerformed
        int selection;
        selection = JOptionPane.showConfirmDialog(rootPane, "Are you sure ?","Logout",JOptionPane.YES_NO_OPTION);
        
        if (selection==JOptionPane.YES_OPTION){
            FrmLogin frmLogin = new FrmLogin();
            this.setVisible(false);
            frmLogin.setVisible(true);
        }
        
    }//GEN-LAST:event_MnuSesionActionPerformed

    private void itemOrderingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOrderingActionPerformed
        FrmOrder frmOrder =new FrmOrder();
        this.setVisible(false);
        frmOrder.setVisible(true);
    }//GEN-LAST:event_itemOrderingActionPerformed

    private void ItemRegisterChefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemRegisterChefActionPerformed
        FrmChef frmChef = new FrmChef();
        this.setVisible(false);
        frmChef.setVisible(true);
    }//GEN-LAST:event_ItemRegisterChefActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FrmListOrder frmListOrder = new FrmListOrder();
        this.setVisible(false);
        frmListOrder.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemRegisterChef;
    private javax.swing.JMenuItem ItemRegisterCustomer;
    private javax.swing.JMenuItem MnuClose;
    private javax.swing.JMenu MnuCustomer;
    private javax.swing.JMenu MnuFarRestaurant;
    private javax.swing.JMenuItem MnuSesion;
    private javax.swing.JMenuItem itemOrdering;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu mnuOrder;
    // End of variables declaration//GEN-END:variables
}
